### ISSUE TITLE
Service file should have "forking", not "forked"

### ISSUE THREAD

**Issue by snej** [fordsfords/blink#2]
The service file produces a warning in syslog saying it doesn't recognize `forks`. It should be `forking` instead.

```
Jun 26 19:02:22 chip systemd[1]: [/etc/systemd/system/blink.service:6] Failed to parse service type, ignoring: forked
```

**Comment by fordsfords** [comment]
Thanks for raising this. Somebody else gave me the service file and I just took it without learning enough to understand it.  Now that I look into it, I see that "forking" is not the correct option for blink.  It is a "simple".  And as it happens, "simple" is the default, so when it ignored "fork", it ended up doing the right thing.  Two wrongs making a right.  :-)

I'll change it to "simple", and I'll brush up on the rest of it as well.

**Comment by snej** [comment]
Thanks! I don't know about service files either (I'm a Mac guy), but after I saw that error I looked through some other service files on my machine and saw `forking`... :)

**Comment by fordsfords** [comment]
OK, should be fixed now.  I checked /var/log/messages and don't see the error.
