### ISSUE TITLE
adjust time of button press?

### ISSUE THREAD

**Issue by ghost** [fordsfords/blink#3]
Hi,

Using PocketCHIP, the reset button is also the home button whereby a brief press brings you back to the desktop.  If you use blink, you can no longer return to the desktop without closing your foreground window.  

Is there a way to configure a time delay into blink? i.e. if i press the button do nothing but if I hold it for 2sec that means graceful shutdown?

**Comment by fordsfords** [comment]
Short answer: not easily.  The AXP209 device times the button press and differentiates between a "short" and a "long".  I don't believe there is any way to ask it how long it was pressed.  "Short" sets a status bit that I read.  Hold it down for 8 seconds (I think) and the AXP just kills power (it is the "force off" function).

That said, I do have a plan to add an option for blink to monitor a GPIO input.  One could install a push button on an XIO pin, and for that, blink could easily time the press and do what you're requesting.

But I have a question.  The primary purpose of blink was for embedded applications where there is no GUI.  CHIP and PocketCHIP's GUI has the shutdown function available a click or two away.  Is there a specific reason you want to use blink with PocketCHIP?

**Comment by ghost** [comment]
One of the first immediate problems I ran into with the PocketCHIP is if I manage to lock myself out of the  standard GUI I have no way to do a graceful shutdown.   Blink solves this problem, but it also steals the home button.   Having thought about this further, I realize it may be a -better- option to think of a key combination I could use instead to cause a graceful shutdown.

**Comment by fordsfords** [comment]
Hi docjkl.  As you may have noticed, the latest version of blink allows you to disable monitoring of the home (reset) button and instead specify a GPIO pin and/or the battery level as the shutdown trigger.
