### ISSUE TITLE
unary operator expected

### ISSUE THREAD

**Issue by nalakawula** [fordsfords/blink#4]
Hi, i live your blink program. I want to report that i ecounter an unary operator expected from syslog.
Here:
_Sep  6 09:26:05 chip blink.sh[363]: /usr/local/bin/blink.sh: line 169: [: 100: unary operator expected_

Thanks

**Comment by fordsfords** [comment]
Hello sumarouno.  That problem was fixed on 28-Aug-2016.  Since then, on 5-Sep-2016, I made another minor improvement related to logging.

If this doesn't fix the problem for you, let me know the version you are running.

**Comment by nalakawula** [comment]
my blink version is 5-sep-2016. And my chip os version is 4.4.
Thanks

**Comment by fordsfords** [comment]
Hmm ... version 5-sep-2016 has the "unary operator expected" error?

Can you please give me your config file?  /usr/local/etc/blink.cfg

Also, please try to manually run it to see if the same error shows up:

sudo /usr/local/bin/blink.sh

Let me know if it still shows up, and give me an exact cut-and-paste of the command line and output.  Thanks.

**Comment by nalakawula** [comment]
Here my /usr/local/etc/blink.cfg

```
# blink.cfg -- version 28-Aug-2016
# Configuration for /usr/local/bin/blink.sh which is normally
# installed as a service started at bootup.
# See https://github.com/fordsfords/blink/tree/gh-pages

MON_RESET=1       # Monitor reset button for short press.
#MON_GPIO=XIO_P7   # Which GPIO to monitor.
#MON_GPIO_VALUE=0  # Indicates which value read from MON_GPIO initiates shutdown.
#MON_BATTERY=10    # When battery percentage is below this, shut down.

BLINK_STATUS=1    # Blink CHIP's status LED.
#BLINK_GPIO=XIO_P6 # Blink a GPIO.

```

here the output of sudo /usr/local/bin/blink.sh : 

```
chip@chip:~$ sudo /usr/local/bin/blink.sh
[sudo] password for chip: 
blink: starting
/usr/local/bin/blink.sh: line 169: [: 100: unary operator expected
/usr/local/bin/blink.sh: line 169: [: 100: unary operator expected
/usr/local/bin/blink.sh: line 169: [: 100: unary operator expected
/usr/local/bin/blink.sh: line 169: [: 100: unary operator expected
/usr/local/bin/blink.sh: line 169: [: 100: unary operator expected
/usr/local/bin/blink.sh: line 169: [: 100: unary operator expected
/usr/local/bin/blink.sh: line 169: [: 100: unary operator expected
/usr/local/bin/blink.sh: line 169: [: 100: unary operator expected
/usr/local/bin/blink.sh: line 169: [: 100: unary operator expected
^Cblink: stopped

```

**Comment by fordsfords** [comment]
Thank you!  I didn't test it adequately.  :-(

Should be fixed now.
Steve
