### ISSUE TITLE
Consuming lots of CPU

### ISSUE THREAD

**Issue by gabrielmcf** [fordsfords/blink#5]
I'm using blink for 1 day and have noticed it's using almost 100% CPU in my CHIP. When i stop the service it drops back to 2% (with 40% peek). Is there anything that can be done?
(Great job! it works very well, besides the CPU consumption)

**Comment by fordsfords** [comment]
Yikes!!!  That should not be.  I will check on that when I get home.

Did you change the configuration?  Also, what kernel version are you running?

**Comment by fordsfords** [comment]
Also, what version of blink are you running?  Enter:
    head -2 /usr/local/bin/blink.sh

**Comment by fordsfords** [comment]
I've just fixed a bug which produced high CPU consumption.  The new version is "13-Sep-2016".  Give it a try and let me know if the problem still exists, or if some other issue comes up.

Thanks!
Steve

**Comment by gabrielmcf** [comment]
Great job! It fixed the CPU issue and the fast blinking (didn't noticed it was a problem...)! Thank you very much!
