### ISSUE TITLE
very fast blinking

### ISSUE THREAD

**Issue by cpagura** [fordsfords/blink#6]
I'm using now kernel 4.4 
the new version of blink now is now blinking furiously fast ... like five per second

**Comment by cpagura** [comment]
the working config file is now in /usr/local/etc/blink.cfg not in usr/local/bin/...

**Comment by fordsfords** [comment]
Thanks for the doc correction.

Regarding the fast blink, I should have documented that if the battery level is equal to the configured threshold, it does a fast blink.  Once the battery level drops below, it does the shutdown.  Above the threshold, it should blink slowly.

Are you seeing fast blink when the battery charge is above the threshold?

**Comment by cpagura** [comment]
Dear Steve,

I’m using a power supply to feed the CHIP, no battery connected, but I commented the relative line in the configuration file. Here my file now in /usr/local/etc/blink.cfg:

# blink.cfg -- version: "10-Sep-2016"

# Configuration for /usr/local/bin/blink.sh which is normally

# installed as a service started at bootup.

# See https://github.com/fordsfords/blink/tree/gh-pages

MON_RESET=1       # Monitor reset button for short press.

#MON_GPIO=XIO_P7   # Which GPIO to monitor.

#MON_GPIO_VALUE=0  # Indicates which value read from MON_GPIO initiates shutdown.

#MON_BATTERY=10    # When battery percentage is below this, shut down.

BLINK_STATUS=1    # Blink CHIP's status LED.

#BLINK_GPIO=XIO_P6 # Blink a GPIO.

It seems that now the blinking frequency, determined “fast” by the absence of battery, don’t care of MON_BATTERY control status, that in my case is not activated … no battery - no control of battery! J

Best regards

Cesare

PS BTW the command “top” indicates cpu usage around 20-23%, is it correct?

Da: Steve Ford [mailto:notifications@github.com] 
Inviato: lunedì 12 settembre 2016 22:40
A: fordsfords/blink blink@noreply.github.com
Cc: cpagura cesare.pagura@cnr.it; Author author@noreply.github.com
Oggetto: Re: [fordsfords/blink] very fast blinking (#6)

Thanks for the doc correction.

Regarding the fast blink, I should have documented that if the battery level is equal to the configured threshold, it does a fast blink. Once the battery level drops below, it does the shutdown. Above the threshold, it should blink slowly.

Are you seeing fast blink when the battery charge is above the threshold?

**Comment by fordsfords** [comment]
I found the bug and created version "13-Sep-2016".  It should fix the very fast blink and the high CPU consumption.  If it doesn't fix the issue, or if some other issue comes up, please let me know.

Thanks!
Steve
