### ISSUE TITLE
Disabling Short Press on PocketCHIP; Still Turns It Off

### ISSUE THREAD

**Issue by nearlyNonexistent** [fordsfords/blink#8]
Title is about all there is to it. Is this a bug with 4.4 or am I doing something wrong? I put a hashtag on the default config's option for short presses before the line itself, and changed nothing else.

**Comment by fordsfords** [comment]
Hi Nearly.  Sorry for the long delay in responding ... work has been crushing.

If I'm not mistaken, PocketCHIP has its own software that monitors for short button presses.

If you think blink is doing it, you can enter:

    grep blink /var/log/syslog

That will tell you what blink thinks it is doing.

One final possibility: if blink is not able to read its config file, then it defaults to monitoring the reset button.  Is it possible the config file is not readable, or isn't in the right place?  Try this:

    ls -l /usr/local/etc/blink.cfg

**Comment by fordsfords** [comment]
I'm closing this issue.  If you still have trouble and want help, either reopen this or open a new ticket.
